tgvashworth/fetch-engine

package.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/phuu/fetch-engine/7)
=> Fix `npm test` infinite recursion ➿

package.json, src/.d.test.ts, src/.d.ts, src/composeEvery.test.ts, src/composeEvery.ts, src/getBoundImplementations.test.ts, src/getBoundImplementations.ts, src/index.test.ts, src/index.ts, tsconfig.json
=> Compose request-phase boolean plugin functions

.travis.yml
=> chore: add travis file

src/composeEvery.ts, src/composePromise.test.ts, src/composePromise.ts, src/index.ts, tsconfig.json
=> feat: compose promises for get methods

src/.d.ts, src/composeVoid.test.ts, src/composeVoid.ts, src/index.ts, tsconfig.json
=> feat: compose void plugin methods

src/composePromise.ts
=> fix: compose promise construcs a single function

src/.d.ts, src/Body.test.ts, src/Body.ts, tsconfig.json
Doesn't deal with environment specific support yet.
=> Added minimum viable Body class

src/.d.test.ts, src/.d.ts, src/Body.ts, src/Request/index.test.ts, src/Request/index.ts, src/fetch.ts, src/utils/http.ts, src/utils/mocks.ts, tsconfig.json
Hey, @phuu stole my Body commit. Bad OSS manners :-1:
=> feat: Implement Request class and tests

README.md, src/.d.ts, src/FetchGroup.test.ts, src/FetchGroup.ts, src/fetchEngine.test.ts, src/fetchEngine.ts
=> chore: rename fetch to fetching

README.md, src/.d.ts, src/FetchGroup.test.ts, src/FetchGroup.ts, src/utils/composeContinuation.test.ts, src/utils/composeContinuation.ts, tsconfig.json
=> Fetch method

package.json
=> test: add ghooks

src/.d.ts, src/FetchGroup.test.ts, src/FetchGroup.ts, src/fetchEngine.test.ts, src/fetchEngine.ts
=> feat: fetch engine calls plugin fetch

README.md
=> Update README with new `fetchEngine` behaviour.

src/Body.test.ts, src/Body.ts, src/Response/Response.test.ts, src/Response/Response.ts
=> Response fixes

.travis.yml
=> chore: remove travis npm upgrade

package.json, src/test-browser.ts, src/test-globals.ts, tsconfig.json
=> chore: add test-globals file to shim in tests

src/fetch-engine-browser.test.ts, src/fetch-engine-browser.ts, tsconfig.json
=> test: first test of browser fetch-engine

tsconfig.json
=> chore: add sourcemap support

package.json, src/.d.ts, src/fetch/fetch-browser.test.ts, src/fetch/fetch-browser.ts, src/integration-tests/routes.ts
=> feat: headers, put, delete and tests

src/fetchEngine.test.ts, src/fetchEngine.ts
As documented (oops) you should be able to pass `FetchGroup` options to a `fetchEngine`.
=> feat: allow FetchGroup opts as arguments to fetchEngine

README.md
=> docs: document fetch requirement
